# SPDX-FileCopyrightText: 2026 Claire Tam <claire.tam@student.adelaide.edu.au>
# SPDX-FileCopyrightText: 2026 fractuscontext <106440141+fractuscontext@users.noreply.github.com>
#
# SPDX-License-Identifier: LPPL-1.3c

name: Build CTAN Zip (Nix)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      create-release:
        type: boolean
        description: Publish on GitHub Release

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31.10.5
      - uses: Mic92/hestia@v3

      - name: Preheat Nix env
        run: nix develop --command true

      - name: Generate Version Tag
        id: version
        run: |
          VERSION_STR=$(nix develop --command get-version)
          echo "tag=$VERSION_STR" >> $GITHUB_OUTPUT

      - name: Build Package
        run: nix develop --command build-ctan ${{ steps.version.outputs.tag }}

      - name: Rename Package
        run: mv user-persona.tar.gz user-persona-${{ steps.version.outputs.tag }}.tar.gz

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          path: user-persona-${{ steps.version.outputs.tag }}.tar.gz
          compression-level: 0

      - name: Create GitHub Release
        if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.create-release == true)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ steps.version.outputs.tag }}"
          name: "Release ${{ steps.version.outputs.tag }}"
          files: user-persona-${{ steps.version.outputs.tag }}.tar.gz
          generate_release_notes: true
